const UserActionTypes = {
	FETCH_USER: "FETCH_USER",
	FETCH_USER_START: "FETCH_USER_START",
	FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
	FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
	RESET_FILTER: "RESET_FILTER",
};

export default UserActionTypes;
